// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1QQlTqWXD-fVkmpOdQU5R8yTtmHlepBI',
    appId: '1:285329929044:web:2c028d22bf8588e0838ec1',
    messagingSenderId: '285329929044',
    projectId: 'smartfinance-prm393',
    authDomain: 'smartfinance-prm393.firebaseapp.com',
    storageBucket: 'smartfinance-prm393.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bpE4CC_ifCIX_90X0Kh-CJnNqyer06E',
    appId: '1:285329929044:android:71d11df78c9f770d838ec1',
    messagingSenderId: '285329929044',
    projectId: 'smartfinance-prm393',
    storageBucket: 'smartfinance-prm393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk5J6QcfPPd49lg0g8ht0Up3wlzSC6jAE',
    appId: '1:285329929044:ios:664dd8387139a49d838ec1',
    messagingSenderId: '285329929044',
    projectId: 'smartfinance-prm393',
    storageBucket: 'smartfinance-prm393.firebasestorage.app',
    iosBundleId: 'com.example.projectFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk5J6QcfPPd49lg0g8ht0Up3wlzSC6jAE',
    appId: '1:285329929044:ios:664dd8387139a49d838ec1',
    messagingSenderId: '285329929044',
    projectId: 'smartfinance-prm393',
    storageBucket: 'smartfinance-prm393.firebasestorage.app',
    iosBundleId: 'com.example.projectFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1QQlTqWXD-fVkmpOdQU5R8yTtmHlepBI',
    appId: '1:285329929044:web:fa6b18a2f4f504c7838ec1',
    messagingSenderId: '285329929044',
    projectId: 'smartfinance-prm393',
    authDomain: 'smartfinance-prm393.firebaseapp.com',
    storageBucket: 'smartfinance-prm393.firebasestorage.app',
  );
}
